# Generated by Django 4.0.1 on 2022-08-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='answer',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='subject',
            name='board',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='chapter',
            field=models.CharField(choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Dhaka', 'Dhaka')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='option01',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AddField(
            model_name='subject',
            name='option02',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AddField(
            model_name='subject',
            name='option03',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AddField(
            model_name='subject',
            name='option04',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AddField(
            model_name='subject',
            name='question',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='subject',
            name='univercity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(choices=[('Pysics', 'Pysics'), ('Chemistry', 'Chemistry'), ('Higher Math', 'Higher Math'), ('Biology', 'Biology')], default='', max_length=50),
        ),
    ]
