# Generated by Django 4.0.1 on 2022-08-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subject_answer_subject_board_subject_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='chapter',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=50),
        ),
    ]
