# Generated by Django 4.0.1 on 2022-08-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_subject_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(choices=[('Pysics 1st', 'Pysics 1st'), ('Chemistry 1st', 'Chemistry 1st'), ('Higher Math 1st', 'Higher Math 1st'), ('Biology 1st', 'Biology 1st'), ('Pysics 2nd', 'Pysics 2nd'), ('Chemistry 2nd', 'Chemistry 2nd'), ('Higher Math 2nd', 'Higher Math 2nd'), ('Biology 2nd', 'Biology 2nd')], default='', max_length=50),
        ),
    ]
